# Generated by Django 5.0.1 on 2024-04-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='source',
            field=models.CharField(choices=[('0', 'Cá nhân: Ăn uống - Doanh Nghiệp: Trả lương  '), ('1', 'Cá nhân: Quần áo - Doanh Nghiệp: Dịch vụ phát sinh'), ('2', 'Cá nhân: Du lịch, vui chơi giải trí - Doanh Nghiệp: Mặt bằng'), ('3', 'Khác')], max_length=100),
        ),
    ]
