# Generated by Django 5.0.1 on 2024-03-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0007_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('0', 'Tài khoản cá nhân'), ('1', 'Tài khoản doanh nghiệp')], default='0', max_length=100),
        ),
    ]
