# Generated by Django 5.0.1 on 2024-03-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('0', 'Cá nhân: Lương - Doanh Nghiệp: Sản Phẩm  '), ('1', 'Cá nhân: Kinh Doanh - Doanh Nghiệp: Dịch Vụ'), ('2', 'Cá nhân: Phụ Thu Nhập - Doanh Nghiệp: Quảng Cáo'), ('3', 'Khác')], max_length=100),
        ),
    ]
