# Generated by Django 5.0.1 on 2024-04-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
